$ git clone https://github.com/suchiagarwal/UM
print("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>User Management</title>')
print ('</head>')
print ('<body>')
print ('<h2>Please Enter your Email ID</h2>')
print ('<form action="app.py" method="POST">')
print('<input type="text" name="text1">')
print('<input type="submit" name="my-form" value="Submit">')
print('</form>')
print ('</body>')
print ('</html>')
